# Generated by Django 5.2.14 on 2026-05-24 17:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_and_go', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=180, verbose_name='Descripcion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Importe')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['order', 'start_date', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='traveler',
            options={'ordering': ['joined_at'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.AddField(
            model_name='traveler',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de union'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='plan_and_go.trip', verbose_name='Viaje'),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddConstraint(
            model_name='traveler',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='unique_traveler_per_trip'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Pagado por'),
        ),
        migrations.AddField(
            model_name='stop',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='plan_and_go.trip', verbose_name='Viaje'),
        ),
        migrations.AddField(
            model_name='expense',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='plan_and_go.stop', verbose_name='Etapa'),
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('trip', 'order'), name='unique_stop_order_per_trip'),
        ),
    ]
